### ISSUE TITLE
左上角的菜单图标和右上角的搜索好像不太对

### ISSUE THREAD

**Issue by ghost** [sendya/Material_Design_Lite_For_Ghost#1]
rt

**Comment by sendya** [comment]
实在抱歉，你可能需要更换 在线字体库，既 fonts.loacg.com 为  fonts.googleapis.com 或者其他CSS代理，因为我自己的反代googleapis不知道为什么开启了允许跨域然而还是不行。

**Comment by sendya** [comment]
已经更新字体库为本地库文件，位于： ./assets/fonts/*.woff2

**Comment by ghost** [comment]
我直接更新了文件，还是不行。（这回连图标都没了，点击原来图标的位置有效果）周末我试试替换在线字体库

**Comment by sendya** [comment]
项目字体已经是改成了本地字体 ，已经完全没调用在线字体了，你还怎么更新在线字体

**Comment by sendya** [comment]
我测试了一遍，好像还是对的。。难道是我本地环境问题？

**Comment by ghost** [comment]
我在本地测的，用的是中文版的ghost（windows下测试）。这么说来我用原版的在vps上试试

**Comment by sendya** [comment]
好像查出问题来了。我尽快修正吧。
