### ISSUE TITLE
ghost的独立页面显示有问题

### ISSUE THREAD

**Issue by y500** [sendya/Material_Design_Lite_For_Ghost#7]
使用了这个theme，独立页面看上去很怪异，可能是因为没有头部banner的原因

**Comment by sendya** [comment]
最近更新了样式.. 还没更新完成。 建议使用分支 style2 
由于手误原本计划更新在 style2的 被习惯性的 git push -u origin master 直接到了主分支。

**Comment by sendya** [comment]
我尽快更新好样式，然后在回复把
这个是分支链接：https://github.com/sendya/Material_Design_Lite_For_Ghost/tree/style2
